### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by vitaly-t** [sindilevich/connection-string-parser#1]
Good job!

I do not mean to troll or anything, just pointing out that [connection-string] does all this.

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by sindilevich** [comment]
Thank you, @vitaly-t! It is worth it to pointing out the alternatives. That way people have a meaningful choice to make.

I think my ultimate goal was to learn writing a library in `Typescript` and getting to know ways to publish my work on `npm`.
